CREATE TABLE careers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR NOT NULL,
  salary NUMERIC(10, 2),
  location VARCHAR,
  timestamp timestamp default now() NOT NULL
);
